Add rebootReader method
stripe/stripe-terminal-react-native pull request #629
Opened 2024-02-29 10:41 UTC by ianlin-bbpos

## Summary

Add rebootReader method.

## Motivation

Support rebootReader SDK method.

## Testing

- [x] I tested this manually
- [ ] I added automated tests

## Documentation

Select one:

- [ ] I have added relevant documentation for my changes.
- [x] This PR does not result in any developer-facing changes.

2024-02-29 15:39 UTC, bric-stripe requested changes
changes lgtm with a small change request to not clear the connected reader after reboot. I tested this branch and confirmed if auto reconnect is enabled it would lose that state. I think you can just remove that clearing and rely on the existing disconnect callback handling to reset the connected reader state.

2024-03-01 01:59 UTC, ianlin-bbpos commented on src/hooks/useStripeTerminal.tsx
> +    }
yes, I removed the codes and gave a test, it works well then. thanks!

2024-03-01 21:39 UTC, bric-stripe approved these changes
changes lgtm!

2024-03-04 16:34 UTC, nazli-stripe approved these changes

2024-03-04 16:34 UTC, merged