Rename collect input types.
stripe/stripe-terminal-react-native pull request #721
Opened 2024-06-06 02:25 UTC by ianlin-bbpos

## Summary

Rename collect inputs type names to match JS SDK;

## Motivation

The public facing type names for RN SDK is different from the JS SDK. Rename these types for the RN SDK to match that of the JS SDK.

## Testing

- [x] I tested this manually
- [ ] I added automated tests

## Documentation

Select one:

- [ ] I have added relevant documentation for my changes.
- [x] This PR does not result in any developer-facing changes.

2024-06-06 17:04 UTC, zakh-stripe requested changes
Thanks for the changes 👍

2024-06-06 22:11 UTC, nazli-stripe commented on android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
>              "You must provide a collectInputs"
```suggestion
            "You must provide an inputs value"
```

2024-06-07 14:42 UTC, nazli-stripe approved these changes

2024-06-07 14:45 UTC, zakh-stripe approved these changes
lgtm!

2024-06-10 19:02 UTC, merged